---
title: "HDI vs head motion correlation"
output: html_document
date: "2024-06-16"
---

```{r}
library(ggplot2)
library(ggExtra)
library(cowplot)
library(scales)
library(dplyr)
library(purrr)
library(readr)
```

```{r}
library(glue)
link_densities <- c("01", "02", "03", "04", "05")
project_dir <- "/Users/petra/Documents/repos/brain_connectivity_in_chronic_pain/"
data_dir <- glue("{project_dir}/Data/HDIs with metadata")


process_ld <- function(ld) {
  file_path <- file.path(data_dir, paste0("HDIat", ld, "_w_meta_261004.csv"))
  
  df <- read_csv(file_path, show_col_types = FALSE) %>%
    filter(time == 1, !is.na(n_spike_regs_sponpain)) %>%
    mutate(
      is_patient = recode(is_patient, '0' = 'HC', '1' = 'CBP'),
      thresh = sd(n_spike_regs_sponpain[is_patient == "HC"]) * 3,
      is_patient = case_when(
        is_patient == "CBP" & n_spike_regs_sponpain < thresh ~ "LoMo CBP",
        is_patient == "CBP" & n_spike_regs_sponpain >= thresh ~ "HiMo CBP",
        TRUE ~ is_patient
      ),
      is_patient = factor(is_patient, levels = c("HC", "LoMo CBP", "HiMo CBP")),
      link_density = paste0(as.integer(ld)*10, "%")
    ) %>%
    dplyr::select(is_patient, n_spike_regs_sponpain, passes_2mm_criterion, 
                  age, promis_sleep_t1, bpi_intensity_t1, spon_pain_rating_mean, betweenness_bin, degree, clustercoef_bin, eigenvector_centrality_bin, link_density)
  
  return(df)
}

merged <- map_dfr(link_densities, process_ld)
merged <- merged[merged$passes_2mm_criterion == 1, ]
df_ld01 <- merged[merged$link_density == "10%", ]  # cols: is_patient, head motion, HDI metrics at 10% density
```

```{r}
# New density/scatter plot
# y_var = HDI
# x_var = head motion ("n_spike_regs_sponpain"), age, sleep
library(MASS)

plot_jointplot <- function(y_var, y_var_name, x_var, x_var_name, save=FALSE, 
                             save_dir = "../Graphs/correlation HDIs vs head motion",
                             width = 5, height = 3, dpi = 600){
  p <- ggplot(df_ld01, aes_string(x = x_var, 
                          y = y_var,
                          color = "is_patient")) +
    geom_point(alpha = 0.6) +
    geom_smooth(method = MASS::rlm, se = FALSE) +
    theme_classic() +
    labs(x = x_var_name, y = y_var_name) +
    scale_color_manual(values = c(HC = "#E06B58", 
                                  `LoMo CBP` = "#44E7E0", 
                                  `HiMo CBP` = "#596DF4")) +
    theme_minimal() +
    theme(
      panel.grid = element_blank(),
      panel.border = element_blank(),
      panel.background = element_rect(fill = "transparent", color = NA),  # main panel
      plot.background = element_rect(fill = "transparent", color = NA),   # entire plot
      axis.line = element_line(color = "black", size=1),
      axis.ticks = element_line(size = 1),
      axis.text = element_text(size = 10, face="bold"),
      axis.title = element_text(size = 10, face = "bold"),
      plot.title = element_text(size = 12, face = "bold"),
      legend.position = "top",
      legend.title = element_blank(),
      legend.text = element_text(size = 10, face = "bold")
    )
  
  if (x_var == "n_spike_regs_sponpain"){
     p <- p +
    scale_x_continuous(
      trans = sqrt_trans(), 
      breaks = c(0, 10, 50, 100, 250, 500, 1000), 
      labels = c("0", "10", "50", "100", "250", "500", "1000"))
  }
  
  legend <- cowplot::get_legend(p)
  p_no_legend <- p + theme(legend.position = "none")
  p_with_marginals <- ggMarginal(p_no_legend, type = "density", groupColour = TRUE, groupFill = TRUE)
  p_final <- cowplot::plot_grid(legend, p_with_marginals, ncol = 1, rel_heights = c(0.1, 1))

  if (save) {
    if (!dir.exists(save_dir)) dir.create(save_dir, recursive = TRUE)
    filename <- file.path(
      save_dir, paste0("jointplot_robust_2mmFD_", 
                       tolower(gsub(" ", "_", y_var_name)), "_vs_", x_var_name, ".png"))
    ggsave(filename, p_final, width = width, height = height, dpi = dpi)
  }
  
  print(p_final)
  
}
```

```{r}
# HEAD MOTION JOINT PLOTS
plot_jointplot("degree", "Degree", x_var = "n_spike_regs_sponpain", x_var_name = "# high motion volumes", save = TRUE)
plot_jointplot("betweenness_bin", "Betweenness", x_var = "n_spike_regs_sponpain", x_var_name = "# high motion volumes", save = TRUE)
plot_jointplot("clustercoef_bin", "Clustering coef", x_var = "n_spike_regs_sponpain", x_var_name = "# high motion volumes", save = TRUE)
plot_jointplot("eigenvector_centrality_bin", "Eigenvector centr", x_var = "n_spike_regs_sponpain", x_var_name = "# high motion volumes", save = TRUE)
```

```{r}
library(WGCNA)
metrics <- c("betweenness_bin", "degree", "clustercoef_bin", "eigenvector_centrality_bin")

get_robust_cor_in_one_ld <- function(var){
  df_ld01 %>%
    group_by(is_patient) %>%
    summarise(
      metric = var,
      r = round(cor(n_spike_regs_sponpain, .data[[var]], use = "complete.obs"), 2),
      r_bicor = round(WGCNA::bicorAndPvalue(n_spike_regs_sponpain, .data[[var]], use = "pairwise.complete.obs")$bicor[1], 2),
      p = round(WGCNA::bicorAndPvalue(n_spike_regs_sponpain, .data[[var]], use = "pairwise.complete.obs")$p[1], 2))
}

corr_tbl <- map_dfr(metrics, get_robust_cor_in_one_ld)

# Kruskal-Wallis ANOVA
kw_tbl <- map_dfr(metrics, function(var) {
  f <- as.formula(paste(var, "~ is_patient"))
  kw <- kruskal.test(f, data = df_ld01)
  tibble(
    metric = var,
    kw_stat = unname(kw$statistic),
    kw_p    = kw$p.value
  )
})

kw_tbl
corr_tbl
```

```{r}
# AGE JOINT PLOTS
plot_jointplot("degree", "Degree", x_var = "age", x_var_name = "Age", save = TRUE)
plot_jointplot("betweenness_bin", "Betweenness", x_var = "age", x_var_name = "Age", save = TRUE)
plot_jointplot("clustercoef_bin", "Clustering coef", x_var = "age", x_var_name = "Age", save = TRUE)
plot_jointplot("eigenvector_centrality_bin", "Eigenvector centr", x_var = "age", x_var_name = "Age", save = TRUE)
```


```{r}
# SUMMARY CORRELATION ACROSS LDs PLOTS
get_robust_cor_across_lds <- function(metric, correlate_with){
  merged %>%
    group_by(link_density, is_patient) %>%
    summarise(
      r = round(cor(.data[[correlate_with]], .data[[metric]], use = "complete.obs"), 2),
      r_bicor = round(WGCNA::bicorAndPvalue(.data[[correlate_with]], .data[[metric]], use = "pairwise.complete.obs")$bicor[1], 2),
      p = round(WGCNA::bicorAndPvalue(.data[[correlate_with]], .data[[metric]], use = "pairwise.complete.obs")$p[1], 2)) %>%
    mutate(metric = metric)
}

plot_correlation_across_lds <- function(correlate_with, correlate_with_name, metrics){

  corr_tbls <- map_dfr(metrics, get_robust_cor_across_lds, correlate_with = correlate_with)
  corr_tbls <- corr_tbls %>% arrange(is_patient, link_density)
  corr_tbls$metric <- factor(corr_tbls$metric, levels=metrics)
  
  p <- ggplot(corr_tbls, aes(x = link_density, y = r_bicor, color = is_patient, group = is_patient)) +
    geom_point(size = 2.5) +
    geom_line(linewidth = 1) +
    geom_hline(yintercept = 0, linetype="dotted", linewidth=0.5) +
    facet_wrap(~ metric, ncol = 2) +
    scale_color_manual(values = c(HC = "#E06B58",
                                  `LoMo CBP` = "#44E7E0",
                                  `HiMo CBP` = "#596DF4")) +
    labs(x = "Link Density", y = paste0("Correlation: HDI vs ", correlate_with_name)) +
    theme_minimal(base_size = 11) +
    theme(
      panel.grid = element_blank(),
      panel.border = element_blank(),
      panel.background = element_rect(fill = "transparent", color = NA),
      plot.background = element_rect(fill = "transparent", color = NA),
      axis.line = element_line(color = "black", linewidth = 0.8),
      axis.ticks = element_line(linewidth = 0.8),
      axis.text = element_text(size = 10, face = "bold"),
      axis.title = element_text(size = 10, face = "bold"),
      plot.title = element_text(size = 12, face = "bold"),
      legend.position = "top",
      legend.title = element_blank(),
      legend.text = element_text(size = 10, face = "bold"),
      strip.text = element_text(size = 11, face = "bold")
    )
  
  return(p)
}
```


# Robust correlations across link densities (Figure 3 and Supplementary for Figure 5?)
```{r}
metrics <- c("betweenness_bin", "degree", "clustercoef_bin", "eigenvector_centrality_bin")
path = "~/Documents/repos/brain_connectivity_in_chronic_pain/Graphs/correlation HDIs vs covariates/"

p <- plot_correlation_across_lds(
  correlate_with = "n_spike_regs_sponpain", 
  correlate_with_name = "head motion", 
  metrics = metrics)
ggsave(paste0(path, "/robust_cor_head_motion_across_lds_2mmFD.png"), p, width = 8, height = 5, dpi = 400)

p <- plot_correlation_across_lds(
  correlate_with = "promis_sleep_t1", 
  correlate_with_name = "sleep disruption", 
  metrics = metrics)
ggsave(paste0(path, "/robust_cor_sleep_disruption_across_lds.png"), p, width = 6, height = 4, dpi = 400)

p <- plot_correlation_across_lds(
  correlate_with = "age", 
  correlate_with_name = "age",
  metrics = metrics)
ggsave(paste0(path, "/robust_cor_age_across_lds.png"), p, width = 6, height = 4, dpi = 400)
```


#TRAIT vs STATE PAIN
```{r}
df_pain_vis <- merged[merged$link_density=="10%", ]

p <- ggplot(df_pain_vis, aes_string(x = "bpi_intensity_t1", 
                          y = "spon_pain_rating_mean",
                          color = "is_patient")) +
    geom_point(alpha = 0.6) +
    geom_smooth(method = MASS::rlm, se = FALSE) +
    theme_classic() +
    labs(x = "Last week average pain", y = "Current pain") +
    scale_color_manual(values = c(HC = "#E06B58", 
                                  `LoMo CBP` = "#44E7E0", 
                                  `HiMo CBP` = "#596DF4")) +
    theme_minimal() +
    theme(
      panel.grid = element_blank(),
      panel.border = element_blank(),
      panel.background = element_rect(fill = "transparent", color = NA),  # main panel
      plot.background = element_rect(fill = "transparent", color = NA),   # entire plot
      axis.line = element_line(color = "black", size=1),
      axis.ticks = element_line(size = 1),
      axis.text = element_text(size = 10, face="bold"),
      axis.title = element_text(size = 10, face = "bold"),
      plot.title = element_text(size = 12, face = "bold"),
      legend.position = "top",
      legend.title = element_blank(),
      legend.text = element_text(size = 10, face = "bold")
    )

legend <- cowplot::get_legend(p)
p_no_legend <- p + theme(legend.position = "none")
p_with_marginals <- ggMarginal(p_no_legend, type = "density", groupColour = TRUE, groupFill = TRUE)
p_final <- cowplot::plot_grid(legend, p_with_marginals, ncol = 1, rel_heights = c(0.1, 1))
p_final

hc <- df_pain_vis[df_pain_vis$is_patient=="HC",]
lomo <- df_pain_vis[df_pain_vis$is_patient=="LoMo CBP",]
himo <- df_pain_vis[df_pain_vis$is_patient=="HiMo CBP",]

WGCNA::bicorAndPvalue(
  hc$spon_pain_rating_mean, hc$bpi_intensity_t1, 
  use = "pairwise.complete.obs")

WGCNA::bicorAndPvalue(
  lomo$spon_pain_rating_mean, lomo$bpi_intensity_t1, 
  use = "pairwise.complete.obs")

WGCNA::bicorAndPvalue(
  himo$spon_pain_rating_mean, himo$bpi_intensity_t1, 
  use = "pairwise.complete.obs")


kruskal.test(spon_pain_rating_mean ~ bpi_intensity_t1, data = df_pain_vis)
```




